import BGParticles from '@/Components/BGParticles';
import './globals.css'
import Navbar from '@/views/Navbar';
import { Azeret_Mono, Jockey_One } from 'next/font/google'
import { Suspense } from 'react';

const azret = Azeret_Mono({ subsets: ['latin'] });
const jockey = Jockey_One({ subsets: ["latin"], weight: ['400'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${azret.className} ${jockey.className}`}>
      <body className="relative ">
        <BGParticles />
        <div className="absolute inset-0 z-above-bg">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  )
}
